# Generated by Django 2.2.4 on 2019-08-29 15:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_service', models.TextField(verbose_name='modalités de prestation')),
                ('status', models.BooleanField(default=False, verbose_name='voté')),
                ('evaluation', models.FloatField(verbose_name='évaluation')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('description', models.TextField(default='ensemble de services a la personnes (SAP)', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('custumuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
                'ordering': ['-id'],
            },
            bases=('jobado.custumuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobado.Category', verbose_name='categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completion_date', models.DateField(verbose_name='date de réalisation')),
                ('completion_hour', models.TimeField(verbose_name='heure de réalisation')),
                ('expiration_date', models.DateField(verbose_name="date d'expiration")),
                ('jobbers_number', models.PositiveIntegerField(default=1, verbose_name='nombre nécessaire de jobbers')),
                ('unit_price', models.PositiveIntegerField(verbose_name='remunération par jobber')),
                ('state', models.BooleanField(default=False, verbose_name='état')),
                ('realised', models.PositiveIntegerField(default=0, verbose_name='réalisé')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date de publication')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='jobado.Poster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobado.Service')),
            ],
            options={
                'verbose_name': 'Job',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='attachments/', verbose_name='contenu')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobado.Application', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='jobado.Job', verbose_name='job'),
        ),
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('poster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobado.Poster')),
                ('biography', models.TextField(verbose_name='mini biographie')),
                ('note', models.FloatField(default=0)),
                ('categories', models.ManyToManyField(db_table='category_jobber', related_name='jobbers', to='jobado.Category')),
            ],
            options={
                'verbose_name': 'Jobber',
                'ordering': ['-id'],
            },
            bases=('jobado.poster',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='jobber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobado.Jobber'),
        ),
    ]
